name: Build and Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  IMAGE_NAME: mdjeee/wodcrmapi

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t $IMAGE_NAME .

      - name: Publish image to docker hub
        run: docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Image from docker hub
        run: docker pull $IMAGE_NAME:latest

      - name: Delete old container
        run: |
          docker stop wodcrmapi-container || true
          docker rm wodcrmapi-container || true

      - name: Run docker container
        run: |
          docker run -d \
            -p 8080:8080 \
            --name wodcrmapi-container \
            --restart unless-stopped \
            $IMAGE_NAME:latest