name: Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run:  |
          mvn clean package -X -DskipTests
          ls -la target/

      - name: Install SSH key
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add EC2 to known hosts
          ssh-keyscan ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Debug: Show files being deployed
          echo "Files to deploy:"
          ls -la target/*.jar
          ls -la deploy.sh
          ls -la src/main/resources/application.properties

          # Copy all necessary files
          scp -v -i ~/.ssh/id_rsa target/wodcrmapi-*.jar ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/wodcrmapi.jar
          scp -v -i ~/.ssh/id_rsa src/main/resources/application.properties ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/
          scp -v -i ~/.ssh/id_rsa deploy.sh ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/

          # Verify files on server
          ssh -v -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} "
            echo 'Files on server:';
            ls -la /home/ubuntu/;
            cat /home/ubuntu/deploy.sh;
            chmod +x /home/ubuntu/deploy.sh
          "

          # Execute deployment
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} "/home/ubuntu/deploy.sh"

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} "
          echo 'Deployment log:';
          cat /home/ubuntu/deploy.log;
          echo 'Application log tail:';
          tail -n 20 /home/ubuntu/app.log;
          echo 'Running processes:';
          pgrep -f 'java -jar' || echo 'No Java process running'
          "