name: Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run:  |
          mvn clean package -X -DskipTests
          ls -la target/

      - name: Install SSH key
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add EC2 to known hosts
          ssh-keyscan ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Find the JAR file
          JAR_FILE=$(ls target/*.jar)

          # Copy files with verbose logging
          scp -v -i ~/.ssh/id_rsa $JAR_FILE ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/
          scp -v -i ~/.ssh/id_rsa src/main/resources/application.properties ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/

          # Run deployment script
          ssh -v -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} "chmod +x deploy.sh && ./deploy.sh"